### ISSUE TITLE
The serve command requires to be run in an Angular project, but a project definition could not be found.

### ISSUE THREAD

**Issue by contiIndia** [sangwin/Angular-5-Sample-Demo#1]
hello dear I am very new in web development as having my background in native app dev. I am facing this issue when I hit ng serve command in the terminal. I can easily serve my newly created project. Can you please help me in this also I am in the project directory only.

**Comment by sangwin** [comment]
Hello, This version is older now. You can check out new repo I have created.

Follow the link : [https://github.com/sangwin/Angular7-CRUD](https://github.com/sangwin/Angular7-CRUD)

Let me know if you find any issues there.
